### ISSUE TITLE
Feature To-Do List

### ISSUE THREAD

**Issue by JamesPeters98** [JamesPeters98/ChestsPlusPlus#4]
- [ ] Create Public Chests
- [ ] Auto Sorting
- [ ] List of chests command
- [ ] Method to check members of a chest! (Probably a command & Lore thing)

**Comment by qantourisc** [comment]
- [ ] Inverted filter

**Comment by JamesPeters98** [comment]
> - [ ] Inverted filter

Good idea, I’ll have to think how to implement it - maybe if the item frame rotation is horizontal.

**Comment by qantourisc** [comment]
- [ ] Fuzzy match (i.e.: oak_sign / spruce_sign)
Tell me if you want me to create a function that is capable of doing this.

**Comment by JamesPeters98** [comment]
> * [ ]  Fuzzy match (i.e.: oak_sign / spruce_sign)
>   Tell me if you want me to create a function that is capable of doing this.
>   Looking at the list.
>   It's going to be hard to decide if ACACIA_LOG should filter all logs, or if it should filter all ACACIA.
>   Maybe a configuration setting ?

Yeah I imagine it would have to be done using a pre-defined list of items that group together the different types of materials e.g

group: ACACIA {
    ACACIA_BOAT
    ACACIA_BUTTON
    ACACIA_DOOR
}

And I'm not sure if it's worth the work considering you can already put multiple item frames on a hopper and have multiple hoppers on the same group of chest.

**Comment by proy27** [comment]
- [ ] Daily Backup

**Comment by kellyph** [comment]
i have found a bug i think.   the crafting table AutoCraft will not recognize the kelp block as a crafting recipe

**Comment by JamesPeters98** [comment]
> i have found a bug i think. the crafting table AutoCraft will not recognize the kelp block as a crafting recipe

This is the feature request thread, but also this is a known bug to do with ComplexRecipes and the Bukkit API!

**Comment by kellyph** [comment]
ok sorry i did not know it was a knowen bug

**Comment by pkristian** [comment]
> > * [ ]   Fuzzy match (i.e.: oak_sign / spruce_sign)
> >   Tell me if you want me to create a function that is capable of doing this.
> >   Looking at the list.
> >   It's going to be hard to decide if ACACIA_LOG should filter all logs, or if it should filter all ACACIA.
> >   Maybe a configuration setting ?
> 
> Yeah I imagine it would have to be done using a pre-defined list of items that group together the different types of materials e.g
> 
> group: ACACIA {
> ACACIA_BOAT
> ACACIA_BUTTON
> ACACIA_DOOR
> }
> 
> And I'm not sure if it's worth the work considering you can already put multiple item frames on a hopper and have multiple hoppers on the same group of chest.

regarding this, where can one find lists of groups, so i can check before i add it in game? (alternativelly alter it) (1.16.3)

thank you

**Comment by BenisonQPS** [comment]
Like pkristian, I would also love to have the group list. Thanks. James, you can message me Directly though Discord BenisonQPS #8300. I have a couple of items that may be of some help RE: List Sorting.

**Comment by M45T3Ryu** [comment]
Allow our own pre-set lists

I been wanting to filter all the Ore's in a single chest but I can't all the log types go to the same chest tho

**Comment by digjn** [comment]
I would like to be able to have different inventories on different worlds hosted on the same server.
